// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8qjljzQITFc4Tz8RBZKZ0AOq7fN2xT0s',
    appId: '1:335008170716:web:8112ad3532f14b82ba2a19',
    messagingSenderId: '335008170716',
    projectId: 'mail-archieve-1b4e6',
    authDomain: 'mail-archieve-1b4e6.firebaseapp.com',
    storageBucket: 'mail-archieve-1b4e6.firebasestorage.app',
    measurementId: 'G-0MMV88KC5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBNXeSo3ud5yXdChz0-spmvF2tJyHsBr4',
    appId: '1:335008170716:android:d1e0fefc16123a6fba2a19',
    messagingSenderId: '335008170716',
    projectId: 'mail-archieve-1b4e6',
    storageBucket: 'mail-archieve-1b4e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAce0IenW-pSb0pOtItXf4Mve_kVPBZjmU',
    appId: '1:335008170716:ios:066de70a03901fb0ba2a19',
    messagingSenderId: '335008170716',
    projectId: 'mail-archieve-1b4e6',
    storageBucket: 'mail-archieve-1b4e6.firebasestorage.app',
    iosBundleId: 'com.example.mailArchieveWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAce0IenW-pSb0pOtItXf4Mve_kVPBZjmU',
    appId: '1:335008170716:ios:066de70a03901fb0ba2a19',
    messagingSenderId: '335008170716',
    projectId: 'mail-archieve-1b4e6',
    storageBucket: 'mail-archieve-1b4e6.firebasestorage.app',
    iosBundleId: 'com.example.mailArchieveWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8qjljzQITFc4Tz8RBZKZ0AOq7fN2xT0s',
    appId: '1:335008170716:web:b6815efc66cd461cba2a19',
    messagingSenderId: '335008170716',
    projectId: 'mail-archieve-1b4e6',
    authDomain: 'mail-archieve-1b4e6.firebaseapp.com',
    storageBucket: 'mail-archieve-1b4e6.firebasestorage.app',
    measurementId: 'G-LXDV0SQ87G',
  );
}
